# OAuth HTTPS Proxy Client Configuration File
# Save as ~/.oauth-proxy-client.yml

# Configuration profiles for different environments
profiles:
  # Default profile (used when no --profile specified)
  default:
    api_url: http://localhost:80
    token: ${ADMIN_TOKEN}  # Reference environment variable
    output_format: table
    log_level: INFO
    
  # Production environment
  production:
    api_url: https://api.proxy.example.com
    token: ${PROD_TOKEN}
    output_format: json
    log_level: WARNING
    admin_email: admin@example.com
    
  # Development environment
  dev:
    api_url: http://localhost:9000
    token: dev_token_abc123
    output_format: table
    log_level: DEBUG
    admin_email: dev@example.com
    
  # Testing environment
  test:
    api_url: ${TEST_API_URL}
    token: ${TEST_TOKEN}
    output_format: json
    log_level: DEBUG

# Default values applied to all profiles
defaults:
  # Timeout settings
  request_timeout: 120
  connect_timeout: 30
  
  # Retry configuration
  max_retries: 3
  retry_delay: 1
  
  # Certificate defaults
  acme_staging_url: https://acme-staging-v02.api.letsencrypt.org/directory
  acme_directory_url: https://acme-v02.api.letsencrypt.org/directory
  
  # OAuth defaults
  base_domain: localhost
  oauth_allowed_github_users: "*"